# Generated by Django 3.2.4 on 2021-09-02 13:29

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_filesblog_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesblog',
            name='file',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=api.models.user_path), size=8), size=8),
        ),
    ]
