# Generated by Django 3.2.4 on 2021-09-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_filesblog_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesblog',
            old_name='file',
            new_name='files',
        ),
    ]
