# Generated by Django 3.2.4 on 2021-09-03 08:02

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_file_filesblog_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesblog',
            name='files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=api.models.user_path), size=8),
        ),
    ]
