# Generated by Django 3.2.4 on 2021-09-03 08:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_filesblog_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesblog',
            name='files',
            field=models.FileField(upload_to=api.models.user_path),
        ),
    ]
