# Generated by Django 3.2.4 on 2021-09-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_filesblog_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilesBlog',
            new_name='FileUpload',
        ),
        migrations.RenameField(
            model_name='fileupload',
            old_name='files',
            new_name='file',
        ),
    ]
