# Generated by Django 3.2.4 on 2021-09-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_fileuploadjodit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploadjodit',
            name='files',
        ),
    ]
