# Generated by Django 3.2.4 on 2021-09-03 20:40

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_fileuploadjodit_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadjodit',
            name='files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=api.models.user_path), null=True, size=None),
        ),
    ]
