# Generated by Django 3.2.4 on 2021-09-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_fileuploadjodit_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='file',
            new_name='image_new',
        ),
    ]
