# Generated by Django 3.2.4 on 2021-09-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_file_fileupload_image_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default='A blog at moh'),
        ),
    ]
