# Generated by Django 3.2.4 on 2021-09-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210904_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadjodit',
            name='path',
            field=models.CharField(default='http://localhost:8000', max_length=50),
        ),
    ]
