# Generated by Django 3.2.4 on 2021-09-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_path_fileuploadjodit_baseurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadjodit',
            name='baseurl',
            field=models.CharField(default='http://localhost:8000/<function user_path at 0x00000219B38A1DC0>', max_length=50),
        ),
    ]
