# Generated by Django 3.2.4 on 2021-09-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_fileuploadjodit_baseurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadjodit',
            name='baseurl',
            field=models.CharField(default='http://localhost:8000', max_length=50),
        ),
    ]
