# Generated by Django 3.2.4 on 2021-09-04 11:12

import api.multiple
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_fileuploadjodit_baseurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadjodit',
            name='files',
            field=api.multiple.ArrayFileField(base_field=models.FileField(upload_to=''), null=True, size=8),
        ),
    ]
